import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Button } from "@/components/ui/button";
import { DotBackground } from "@/components/ui/dot-background";
import SolanaWalletProvider from "@/hooks/wrapper/solana-wallet";
import Header from "@/components/shared/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col h-screen w-screen antialiased`}
      >
        <SolanaWalletProvider>
          <Header />
          {children}
          <DotBackground />
        </SolanaWalletProvider>
      </body>
    </html>
  );
}
