import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { DotBackground } from "@/components/ui/dot-background";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col h-screen w-screen antialiased`}
      >
        <div className="flex h-20 z-20 p-4 w-screen justify-between items-center">
          <h1 className="text-2xl font-bold">💤 DreamWalk</h1>
          <Button>
            Connect Wallet
          </Button>
        </div>
        {children}
        <DotBackground />
      </body>
    </html>
  );
}
